#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Need input file"
    exit
fi

$LLVM_BIN/clang -S -O3 -emit-llvm -mllvm -enable-extract-loop-bodies -mllvm -debug-only=loop-extraction -o /tmp/output.ll $1  

